In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from cmdstanpy import CmdStanModel

import arviz as az

C:\Users\Josh\AppData\Roaming\Python\Python313\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [3]:
# Get data
data = pd.read_csv('data/recognition.csv', header=0, sep=',')
data.head()

# Prepare data in Stan friendly format
data_dict = {
    'N': data.shape[0],
    'old': data.old.values,
    'response': data.response.values
}

In [11]:
# Compile 1HT model
model1 = CmdStanModel(stan_file="hw4_3_1.stan")

21:49:32 - cmdstanpy - INFO - compiling stan file C:\Users\Josh\Box\Documents\COGS-4210_Cognitive_Modeling\Repo\hw4\hw4_3_1.stan to exe file C:\Users\Josh\Box\Documents\COGS-4210_Cognitive_Modeling\Repo\hw4\hw4_3_1.exe
21:49:48 - cmdstanpy - INFO - compiled model executable: C:\Users\Josh\Box\Documents\COGS-4210_Cognitive_Modeling\Repo\hw4\hw4_3_1.exe

In [15]:
# Sample 1HT model
fit1 = model1.sample(data=data_dict, chains=4, iter_sampling=2500, iter_warmup=1000)

# Display sampling diagnostics
print(fit1.diagnose())

21:54:21 - cmdstanpy - INFO - CmdStan start processing
chain 1:   0%|          | 0/3500 [00:00<?, ?it/s, (Warmup)]


chain 1:  29%|██▊       | 1000/3500 [00:00<00:00, 20052.32it/s, (Sampling)]


chain 1:  83%|████████▎ | 2900/3500 [00:00<00:00, 28676.91it/s, (Sampling)]


chain 1: 100%|██████████| 3500/3500 [00:00<00:00, 25992.03it/s, (Sampling completed)]
chain 2: 100%|██████████| 3500/3500 [00:00<00:00, 25875.16it/s, (Sampling completed)]

chain 3: 100%|██████████| 3500/3500 [00:00<00:00, 25904.47it/s, (Sampling completed)]


chain 4: 100%|██████████| 3500/3500 [00:00<00:00, 25920.07it/s, (Sampling completed)]

21:54:21 - cmdstanpy - INFO - CmdStan done processing.

Checking sampler transitions treedepth.
Treedepth satisfactory for all transitions.

Checking sampler transitions for divergences.
No divergent transitions found.

Checking E-BFMI - sampler transitions HMC potential energy.
E-BFMI satisfactory.

Rank-normalized split effective sample size satisfactory for all parameters.

Rank-normalized split R-hat values satisfactory for all parameters.

Processing complete, no problems detected.

In [17]:
# Compile 2HT model
model2 = CmdStanModel(stan_file="hw4_3_2.stan")

21:54:58 - cmdstanpy - INFO - compiling stan file C:\Users\Josh\Box\Documents\COGS-4210_Cognitive_Modeling\Repo\hw4\hw4_3_2.stan to exe file C:\Users\Josh\Box\Documents\COGS-4210_Cognitive_Modeling\Repo\hw4\hw4_3_2.exe
21:55:14 - cmdstanpy - INFO - compiled model executable: C:\Users\Josh\Box\Documents\COGS-4210_Cognitive_Modeling\Repo\hw4\hw4_3_2.exe

In [ ]:
# Sample 2HT model
fit2 = model2.sample(data=data_dict, chains=4, iter_sampling=2500, iter_warmup=1000)

# Display sampling diagnostics
print(fit2.diagnose())

In [ ]:
# Display 1HT sampling data
summary = fit1.summary()
display(summary)

draws_df = fit1.draws_pd()
display(draws_df.head())

# Plot
data1 = az.from_cmdstanpy(posterior=fit1)
_ = az.plot_trace(data1, legend=True, var_names=["d", "g"])
plt.tight_layout()

,Mean,MCSE,StdDev,MAD,5%,50%,95%,ESS_bulk,ESS_tail,ESS_bulk/s,R_hat
lp__,-23.338300,0.015958,1.052820,0.745151,-25.457100,-22.999000,-22.339600,4559.15,5801.93,16167.2,1.00168
d,0.673240,0.001427,0.123818,0.125818,0.453108,0.685498,0.856389,7581.06,6253.28,26883.2,1.00101
g,0.346483,0.001323,0.110215,0.112820,0.175078,0.341189,0.539700,6878.45,6284.28,24391.7,1.00074

,chain__,iter__,draw__,lp__,accept_stat__,stepsize__,treedepth__,n_leapfrog__,divergent__,energy__,d,g
0,1.0,1.0,1.0,-22.301991,0.756848,0.756141,3.0,7.0,0.0,28.807336,0.661971,0.360542
1,1.0,2.0,2.0,-23.919427,0.770761,0.756141,2.0,5.0,0.0,25.321931,0.523453,0.534913
2,1.0,3.0,3.0,-26.142173,0.691569,0.756141,2.0,3.0,0.0,26.932173,0.698227,0.648434
3,1.0,4.0,4.0,-23.270732,0.968576,0.756141,2.0,3.0,0.0,26.860656,0.662520,0.208957
4,1.0,5.0,5.0,-23.432442,0.974833,0.756141,3.0,7.0,0.0,24.085019,0.515020,0.483904

In [ ]:
# Display 2HT sampling data
summary = fit2.summary()
display(summary)

draws_df = fit2.draws_pd()
display(draws_df.head())

# Plot
_ = az.plot_trace(fit2, legend=True)
plt.tight_layout()

# Display sampling diagnostics
print(fit2.diagnose())